## Exercises

In [52]:
import numpy as np

### Exercise 1

Create a 5x5 numpy array of booleans where all values are True apart from the first element of the last row.

In [60]:
x = np.ones((5,5),dtype=bool)
x[4,0] = False
x

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

### Exercise 2

Create a numpy array with values ranging from 1 to 20. Remove the even numbers.

In [61]:
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
x[x%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Exercise 3

Create a 5x5 numpy array and populated with random numbers from a normal distribution (mean=0, std=1). Filter out all the negative values. Change the resulting array to multi-dimensional array where the number of rows will be equal to the number of positive elements and 1 column.

In [63]:
x = np.random.normal(0,1,(5,5))
x 

array([[-1.79966539,  2.3667242 , -0.61462058, -1.06618465, -0.64145652],
       [ 1.03901354,  0.54233745,  1.60144415, -1.76095182,  0.60788325],
       [ 0.5990161 , -1.03980567,  1.2068951 , -1.90314966,  0.24857064],
       [ 1.31501687,  1.31747029,  0.74440524, -0.78292883,  0.26704688],
       [-1.53116731, -0.87279545, -1.02253383, -1.09636819, -0.75401669]])

In [64]:
x[x>0].reshape(-1,1)

array([[2.3667242 ],
       [1.03901354],
       [0.54233745],
       [1.60144415],
       [0.60788325],
       [0.5990161 ],
       [1.2068951 ],
       [0.24857064],
       [1.31501687],
       [1.31747029],
       [0.74440524],
       [0.26704688]])

### Exercise 4

Create a 10x10 identity matrix of integer type. Save the matrix in csv format using a file name of your choice. Load back the matrix.

In [65]:
I = np.eye(10,10,dtype='int')
I

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [66]:
np.savetxt('identity_matrix.csv',I, delimiter=',')

In [67]:
identity_matrix = np.loadtxt('identity_matrix.csv', delimiter=',')
identity_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Exercise 5

Create a 5x5 numpy array populated by random integers ranging from 1 to 100. Calculate the sum of rows, columns and of the diagonal elements.

In [69]:
z = np.random.randint(1,101,size=25).reshape((5,5))
z

array([[73, 78, 97, 97, 95],
       [72, 84, 49,  1, 73],
       [43,  4, 53, 31, 77],
       [35, 53, 83, 53, 27],
       [77, 69, 54, 87, 34]])

In [70]:
z.sum(axis=1)

array([440, 279, 208, 251, 321])

In [71]:
z.sum(axis=0)

array([300, 288, 336, 269, 306])

In [72]:
np.diag(z).sum()

297

### Exercise 6

Create a 4x3 numpy array and populated with random integers ranging from 1 to 20. Estimate it's transpose. Multiply the two arrays.

In [73]:
y = np.random.randint(1,21,size=12).reshape((4,3))
y

array([[ 5,  2,  9],
       [15, 20, 11],
       [ 7, 11, 15],
       [10,  9, 10]])

In [74]:
y_T = y.T
y_T

array([[ 5, 15,  7, 10],
       [ 2, 20, 11,  9],
       [ 9, 11, 15, 10]])

In [75]:
y.dot(y_T)

array([[110, 214, 192, 158],
       [214, 746, 490, 440],
       [192, 490, 395, 319],
       [158, 440, 319, 281]])

### Exercise 7

Create a 2x4 and a 4x4 numpy arrays. Populate them with random integers ranging from 80 to 100. Join them either vertically or horizontally.

In [76]:
x = np.random.randint(80,101,size=8).reshape((2,4))
x

array([[96, 95, 93, 95],
       [85, 87, 99, 87]])

In [77]:
z = np.random.randint(80,101,size=16).reshape((4,4))
z

array([[ 96,  94,  98,  88],
       [ 90,  83,  81,  84],
       [100,  89, 100,  86],
       [100,  93,  90,  95]])

In [78]:
np.vstack([x,z])

array([[ 96,  95,  93,  95],
       [ 85,  87,  99,  87],
       [ 96,  94,  98,  88],
       [ 90,  83,  81,  84],
       [100,  89, 100,  86],
       [100,  93,  90,  95]])

### Exercise 8

Create a 4x4 numpy array and populate with numbers originating from the standard normal distribution (mean=0, std=1). Change all negative numbers to missing. Calculate the sum of all the numbers.

In [79]:
z = np.random.normal(0,1,(4,4))
z

array([[ 1.38391553, -0.38444757, -0.18103868, -0.57665233],
       [ 0.2465454 , -1.12101577, -1.07241391, -0.9577624 ],
       [-0.1113773 ,  0.87539514,  2.00990107,  0.42753398],
       [-0.50762431,  0.87696068, -1.20370658, -0.30075403]])

In [80]:
z[z < 0] = np.nan
z

array([[1.38391553,        nan,        nan,        nan],
       [0.2465454 ,        nan,        nan,        nan],
       [       nan, 0.87539514, 2.00990107, 0.42753398],
       [       nan, 0.87696068,        nan,        nan]])

In [81]:
np.sum(z)

nan

In [82]:
np.nansum(z)

5.820251804415929

### Exercise 9

As Exercise 8 but without affecting the original array.

In [83]:
z = np.random.normal(0,1,(4,4))
z

array([[ 0.76699451, -0.34710582,  0.22246955,  0.20562044],
       [-0.59134437, -0.53319631, -0.29222972,  0.23332592],
       [ 0.73554138,  1.25048356, -0.88315744,  0.08701086],
       [-0.20069209, -0.5694384 ,  0.59696977,  0.13010978]])

In [35]:
z_new = np.where(z<0,np.nan,z)

In [84]:
z

array([[ 0.76699451, -0.34710582,  0.22246955,  0.20562044],
       [-0.59134437, -0.53319631, -0.29222972,  0.23332592],
       [ 0.73554138,  1.25048356, -0.88315744,  0.08701086],
       [-0.20069209, -0.5694384 ,  0.59696977,  0.13010978]])

In [85]:
z_new

array([[0.7329518 ,        nan,        nan, 0.72775977],
       [0.15862388, 1.51095994, 0.63584747,        nan],
       [2.58098063, 0.15917378, 0.18467324,        nan],
       [       nan,        nan, 0.87286398, 0.48556672]])

### Exercise 10

Create a 4x4 numpy array and populate it with random integers ranging from 25 to 50. Calculate the inverse and the pseudo inverse of the array. Multiply the original array with it's inverse.

In [86]:
z = np.random.randint(25,51,size=16).reshape(4,4)
z

array([[40, 41, 35, 48],
       [39, 41, 27, 37],
       [33, 29, 46, 31],
       [28, 38, 25, 34]])

In [87]:
z_inv = np.linalg.inv(z)
z_inv

array([[-0.00369432,  0.11658031,  0.00098748, -0.12255164],
       [-0.07878901,  0.00518135, -0.00095262,  0.10646158],
       [-0.01798369, -0.03626943,  0.04254281,  0.02606938],
       [ 0.10432399, -0.07512953, -0.03103   , -0.00781849]])

In [88]:
z.dot(z_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         3.33066907e-16],
       [-4.44089210e-16,  1.00000000e+00, -2.22044605e-16,
         9.43689571e-16],
       [-4.44089210e-16, -8.88178420e-16,  1.00000000e+00,
         2.77555756e-17],
       [-4.44089210e-16, -4.44089210e-16,  0.00000000e+00,
         1.00000000e+00]])

In [89]:
z_pinv = np.linalg.pinv(z)
z_pinv

array([[-0.00369432,  0.11658031,  0.00098748, -0.12255164],
       [-0.07878901,  0.00518135, -0.00095262,  0.10646158],
       [-0.01798369, -0.03626943,  0.04254281,  0.02606938],
       [ 0.10432399, -0.07512953, -0.03103   , -0.00781849]])

In [90]:
z.dot(z_pinv)

array([[ 1.00000000e+00, -8.88178420e-16,  6.66133815e-16,
         6.10622664e-16],
       [ 0.00000000e+00,  1.00000000e+00,  4.44089210e-16,
         2.33146835e-15],
       [ 0.00000000e+00, -2.22044605e-15,  1.00000000e+00,
         1.85962357e-15],
       [-4.44089210e-16, -1.77635684e-15,  4.44089210e-16,
         1.00000000e+00]])

### Exercise 11

Create two numpy arrays and populate the with 30 random numbers ranging from 1 to 7. Find any elements that match.    

In [91]:
x = np.random.randint(1,7,size=30)
x

array([1, 5, 2, 1, 1, 4, 2, 4, 1, 4, 5, 6, 1, 2, 2, 3, 3, 3, 3, 5, 2, 2,
       1, 2, 6, 5, 2, 1, 2, 2])

In [92]:
z = np.random.randint(1,7,size=30)
z

array([6, 5, 2, 1, 4, 2, 5, 5, 2, 5, 1, 2, 6, 2, 4, 3, 3, 6, 5, 2, 4, 3,
       3, 3, 2, 5, 4, 6, 1, 4])

In [93]:
np.where(x==z)

(array([ 1,  2,  3, 13, 15, 16, 25]),)

### Exercise 12

Create a 5x4 numpy array and populate it with random integers ranging from 1 to 10. Swap the first and third column and the second and fourth row.

In [57]:
x = np.random.randint(1,10,size=20).reshape((5,4))
x

array([[5, 5, 2, 6],
       [1, 9, 8, 8],
       [9, 3, 7, 3],
       [8, 4, 1, 4],
       [5, 6, 7, 4]])

In [58]:
x[:,[2,1,0,3]]

array([[2, 5, 5, 6],
       [8, 9, 1, 8],
       [7, 3, 9, 3],
       [1, 4, 8, 4],
       [7, 6, 5, 4]])

In [59]:
x[[0,3,2,1,4],:]

array([[5, 5, 2, 6],
       [8, 4, 1, 4],
       [9, 3, 7, 3],
       [1, 9, 8, 8],
       [5, 6, 7, 4]])